name: Build and Test website

on:
  workflow_dispatch: {}
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: |
          npm install

      - name: build
        run: |
          npm run build

  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          npm install

      # https://docs.cypress.io/guides/continuous-integration/github-actions
      - name: Cypress run
        # https://github.com/marketplace/actions/cypress-io
        uses: cypress-io/github-action@v4.2.1 # use the explicit version number
        with:
          start: npm run dev -- --host
          wait-on: "http://localhost:3000"
